version: '3'

services:
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - backend
      - default

  resque_web:
    image: resque_web
    depends_on:
      - redis
    build:
      context: .
      dockerfile: worker/Dockerfile.resque_web
    env_file: .env.docker
    ports:
      - 5678:5678
    networks:
      - backend
      - default

  ellie_admin:
    image: ellie_admin
    depends_on:
      - redis
      - ellie_worker
    build:
      context: .
      dockerfile: admin/Dockerfile
    env_file: .env.docker
    ports:
      - 29292:9292
    networks:
      - default
      - backend

  ellie_web:
    image: ellie_web
    depends_on:
      - redis
      - ellie_worker
    build:
      context: .
      dockerfile: api/Dockerfile
    env_file: .env.docker
    ports:
      - 9292:9292
    networks:
      - backend
      - default

  ellie_worker:
    image: ellie_worker
    depends_on:
      - redis
    build:
      context: .
      dockerfile: worker/Dockerfile
    env_file: .env.docker
    environment:
      - VERBOSE=yes
    networks:
      - backend

networks:
  backend:
